#!/bin/bash
# Setup DNS for WSL
set -e

echo "### 02_set_dns.sh - Setting up DNS for WSL..."

# Check root
if [ "$EUID" -ne 0 ]; then
    echo "❌ Must run as root"
    exit 1
fi

# Backup original
[ -f /etc/resolv.conf ] && [ ! -f /etc/resolv.conf.bak ] && cp /etc/resolv.conf /etc/resolv.conf.bak

# Configure WSL to not auto-generate resolv.conf
if [ ! -f /etc/wsl.conf ] || ! grep -q "generateResolvConf.*false" /etc/wsl.conf; then
    echo "- Configuring /etc/wsl.conf..."
    {
        echo "[network]"
        echo "generateResolvConf = false"
        echo ""
    } > /etc/wsl.conf
fi

# Set DNS servers
dns_servers="${2:-8.8.8.8,1.1.1.1}"
[ "$1" = "--dns" ] && [ -n "$2" ] && dns_servers="$2,8.8.8.8,1.1.1.1"

# Remove existing resolv.conf and create new one
rm -f /etc/resolv.conf
echo "# Generated by 02_set_dns.sh - $(date)" > /etc/resolv.conf
for server in $(echo "$dns_servers" | tr ',' ' '); do
    echo "nameserver $server" >> /etc/resolv.conf
done

echo "✅ DNS configured: $dns_servers"
