#!/bin/bash
# author: viliam batka
set -e
echo "Setting up DNS for WSL..."

# Require root (script should be invoked with -u root)
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (in WSL: wsl -u root ...)"
    exit 1
fi

# Backup once
if [ -f /etc/resolv.conf ] && [ ! -f /etc/resolv.conf.bak ]; then
    cp /etc/resolv.conf /etc/resolv.conf.bak
fi

# Ensure wsl.conf prevents auto-generation (idempotent)
if ! grep -q "generateResolvConf" /etc/wsl.conf 2>/dev/null; then
    printf "[network]\ngenerateResolvConf = false\n" > /etc/wsl.conf
fi

rm -f /etc/resolv.conf

# Get DNS servers from --dns or use fallback
if [ "$1" = "--dns" ] && [ -n "$2" ]; then
    dns_servers="$2,8.8.8.8,1.1.1.1"
else
    dns_servers="8.8.8.8,1.1.1.1"
fi

# Write resolv.conf fresh
echo "# generated by 02_set_dns.sh" > /etc/resolv.conf
for i in $(echo "$dns_servers" | tr ',' ' '); do
    echo "nameserver $i" >> /etc/resolv.conf 
done
echo "Current /etc/resolv.conf content:"
cat /etc/resolv.conf

echo "Current /etc/wsl.conf content:"
cat /etc/wsl.conf